version: 2
jobs:
  build:
    docker:
      - image: kjintroverted/go-node
    working_directory: ~/solid-budget
    steps:
      - checkout
      - run: npm i
      # Add Tests
      - run: npm run build

  deploy:
    docker:
      - image: kjintroverted/go-node
    working_directory: ~/solid-budget
    steps:
      - checkout
      - run: npm i
      - run: npm i surge
      - run: npm run build
      - run: rm -rf .git
      - run: cd build
      - run: echo "https://budget.wkgreen.dev" > CNAME
      - run: git init
      - run: git remote add origin git@github.com:kjintroverted/solid-budget.git
      - run: git branch -m master gh-pages
      - run: git add .
      - run: git commit -m "CI Deploy"
      - run: git push -u origin gh-pages

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
